### ISSUE TITLE
Auto semicolon

### ISSUE THREAD

**Issue by septemhill** [ziglang/zig.vim#21]
Hi, it would be nice to have auto-add semicolon end of the line when save, someone like me (a gopher) always forgot to add it :(

**Comment by YohananDiamond** [comment]
Hmm... how would that work, though?
In zig you can write a statement across multiple lines (even without parens or brackets), and adding a semicolon at the end of all  these lines would cause problems. For example:

```zig
const foo = if (condition)
    value_if_true
else
    value_if_false
```
If we were to add a semicolon to the end each line, this would happen:
```zig
const foo = if (condition);
    value_if_true;
else;
    value_if_false;
```
and it wouldn't work as intended.

Oh, also: I think what would be responsible for doing that could be `zig fmt` (which is automatically called when saving a zig file), and it would make way more sense because it parses the code and would be able to guess where to put the semicolons. I suggest you submit an issue on the [main repository](https://github.com/ziglang/zig/issue) for that.
