### ISSUE TITLE
Cannot redo (C-r) after saving with autoformat

### ISSUE THREAD

**Issue by damienfir** [ziglang/zig.vim#47]
The redo command does not work after saving a file with autoformatting enabled
```
let g:zig_fmt_autosave = 1
```

Steps to reproduce the bug:
1. Make a change
2. Save file
3. Undo change
4. Save file
5. Redo change

The last step does not work.

Tried on neovim v0.4.4

**Comment by LemonBoy** [comment]
This is a [known problem](https://github.com/fatih/vim-go/issues/40), once we reformat the whole buffer the history is truncated because it may not be applicable anymore.
Some solutions using `wundo` and `rundo` exist but they don't solve the underlying problem, even if the remaining part of the history is kept it may produce wrong results when applied.

**Comment by damienfir** [comment]
I understand.
Not sure how it is implemented for https://github.com/Chiel92/vim-autoformat but it seems to work most of the time. Indeed it does not work when the formatting changed the affected line.

**Comment by LemonBoy** [comment]
> Not sure how it is implemented for https://github.com/Chiel92/vim-autoformat but it seems to work most of the time.

It's only side-stepping the problem by not replacing the buffer contents if there's no need to do so, every time it has to modify the buffer contents the same problem appears again.

I'm a bit hesitant to add this check as:
- I didn't want to load both the original and the formatted buffer contents in memory to keep things moving relatively fast
- It only papers over the undo problems in some limited cases

**Comment by damienfir** [comment]
As this is a known problem, we can close this issue since it there is a configuration option to disable autoformat on save.
